lovegaoshi/azusa-player-mobile

package.json, src/components/dialogs/NewPlaylistDialog.tsx, src/components/dialogs/PlaylistSettingsDialog.tsx, src/components/dialogs/RenameSongDialog.tsx, src/components/playlist/BiliSearchbar.tsx, src/components/playlist/PlaylistInfo.tsx, src/components/playlist/PlaylistList.tsx, src/components/playlist/PlaylistMenu.tsx, src/components/playlist/SongInfo.tsx, src/components/playlist/SongMenu.tsx, src/services/PlaybackService.ts, src/utils/BiliFetch.ts, src/utils/DataProcess.js, src/utils/Utils.ts
歌曲菜单（竖三点）功能：
- 改名
- 删除
- 拷贝至另一个歌单
- 在歌单内搜索
- 加入黑名单
其他功能在考虑
=> feat: songmenu functionalities

src/components/playlist/BiliSearchbar.tsx, src/components/playlist/PlaylistList.tsx, src/utils/BiliSubscribe.ts, src/utils/re.ts
pulldown playlist to add new songs found in urls defined in playlist's subscribeUrls.
=> feat: rss update

src/App.tsx, src/components/player/TrackInfo.tsx, src/components/playlists/View.tsx, src/components/setting/SkinSettings.tsx, src/components/style.tsx, src/components/styles/AzusaTheme.tsx
改不动了 @kenmingwang 凑活改改 把azusa-player的css搬过来
=> feat: 烂的阿梓皮肤

index.js, package.json, src/App.tsx, src/components/background/AppOpenSplash.tsx, src/components/buttons/PlaylistSettingsButton.tsx, src/components/buttons/RandomGIF.tsx, src/components/dialogs/CopiedPlaylistDialog.tsx, src/components/dialogs/GenericDialog.tsx, src/components/dialogs/NewPlaylistDialog.tsx, src/components/dialogs/PlaylistSettingsDialog.tsx, src/components/dialogs/PortaledInput.tsx, src/components/dialogs/RenameSongDialog.tsx, src/components/login/Bilibili.tsx, src/components/playlists/View.tsx, src/components/setting/View.tsx, src/localization/en/translation.json, src/localization/zhcn/translation.json, wdyr.ts, yarn.lock
=> fix: textinput cursor flickers inside portal

src/components/player/PlayerControls.tsx, src/components/player/PlayerModeButton.tsx, src/components/player/enums/RepeatMode.ts, src/components/player/usePlayerControls.ts, src/utils/Bilibili/BiliOperate.ts, src/utils/mediafetch/biliavideo.ts
添加了一个新播放模式（四叶草图标）：下一首歌是b站视频相关
挺傻逼的
=> feat: bilisuggest

src/components/player/TrackInfo/SongMenu.tsx, src/components/player/TrackInfo/SongMenuButton.tsx, src/components/player/usePlayerControls.ts, src/utils/Bilibili/BiliOperate.ts
=> Fix: bilisuggest

src/utils/mediafetch/ytbvideo.ts, yarn.lock
react-native-reanimated v3.2 breaks ATM. swipe gesture does not respond. dont upgrade yet.
=> chore: packge upgrade

android/app/build.gradle, package.json, yarn.lock
react-native-share-menu is still on compileSdk 29 so I forked and changed to sdk 33.
=> chore: dep upgrade

.eslintrc.js, .eslintrc.json, .github/workflows/android-release.yml, .github/workflows/android-weekly.yml, android/app/src/main/AndroidManifest.xml, package.json, src/components/background/AppOpenSplash.tsx, src/components/background/MainBackground.tsx, src/components/buttons/PlaylistMenuButton.tsx, src/components/dialogs/GenericCheckDialog.tsx, src/components/dialogs/GenericSelectDialog.tsx, src/components/player/PlayPauseButton.tsx, src/components/player/PlayerModeButton.tsx, src/components/player/ThumbsUpButton.tsx, src/components/style.tsx, src/components/styles/AzusaTheme.ts, src/hooks/useAAPlayback.ts, src/hooks/useSetting.ts, src/services/PlaybackService.ts, src/services/SetupService.ts, src/types/style.d.ts, src/utils/ChromeStorage.ts, yarn.lock
=> feat: thumbs up button

ios/Podfile
i have no idea what this does. time to try if this fixes the IPA release!
=> fix: podfile

src/components/playlist/BiliSearchbar.tsx, src/components/playlist/SearchMenu.tsx, src/enums/Storage.ts, src/utils/BiliSearch.ts, src/utils/ChromeStorage.ts
closes #112 
长按搜索按钮弹出搜索选项可选默认搜索引擎。谢谢你libmuse。
=> feat: 油管搜索

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/noxplay/noxplayer/MainActivity.java, src/App.tsx, src/components/player/Lyric.tsx, src/components/player/PIPLyric.tsx, src/components/player/TrackInfo/TrackInfo.tsx, src/components/playlists/View.tsx, src/enums/View.ts, src/services/PlaybackService.ts, src/stores/appStore.ts, yarn.lock
用画中画模式做桌面歌词。使用setAutoEnterEnabled的原因仅支持安卓13+。有一些骚操作：
在进入画中画的onPause后马上onResume，强行使APM进入前台运行，更新UI
=====
RN社区跟一潭死水一样
https://stackoverflow.com/questions/74673798/how-to-implement-pip-picture-in-picture-mode-in-react-native
https://stackoverflow.com/questions/73337318/react-native-android-picture-in-picture-view-not-updating
=====
closes #111 
now the question is: does this pass the google store review?
=> feat: PIP LyricView

src/components/buttons/PlaylistMenuButton.tsx, src/components/login/Bilibili.tsx, src/components/player/PlayPauseButton.tsx, src/components/playlist/BiliSearchbar.tsx, src/components/playlist/PlaylistInfo.tsx, src/components/playlist/PlaylistList.tsx, src/components/setting/SkinSearchbar.tsx, src/components/setting/sync/GenericSyncButton.tsx, src/components/setting/sync/PersonalSyncButton.tsx
premature release, i want to test pip
=> fix: style

android/app/src/main/java/com/noxplay/noxplayer/MainActivity.java, src/components/playlist/BiliSearchbar.tsx, src/components/setting/SkinSearchbar.tsx, src/components/styles/NoxTheme.ts, src/components/styles/steria.json, src/components/styles/steriaGarb.json
why S21 is such a little bitch, samsung
=> fix: S21 fixes 

src/App.tsx, src/components/player/PlayPauseButton.tsx, src/components/playlist/BiliSearchbar.tsx, src/components/playlist/SearchMenu.tsx, src/components/setting/SkinSettings.tsx, src/components/setting/sync/GenericSyncButton.tsx, src/components/setting/sync/PersonalSyncButton.tsx, src/hooks/useSetting.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Song.ts, src/services/PlaybackService.ts, src/stores/appStore.ts, src/stores/playerSettingStore.ts
=> feat: loadMetadataTrack

src/services/PlaybackService.ts
=> feat: prefetch

.github/workflows/android-weekly.yml, android/app/build.gradle, src/components/buttons/AddPlaylistButton.tsx, src/components/dialogs/GenericDialog.tsx, src/components/dialogs/NewPlaylistDialog.tsx, src/components/dialogs/PlaylistSettingsDialog.tsx, src/components/dialogs/PortaledInput.tsx, src/components/dialogs/RenameSongDialog.tsx, src/components/player/Progress.tsx, src/components/player/TrackInfo/ABSliderMenu.tsx, src/components/player/TrackInfo/SongMenu.tsx, src/components/playlists/View.tsx, src/components/setting/DeveloperSettings.tsx, src/components/setting/GeneralSettings.tsx, src/components/setting/SkinSettings.tsx, src/components/setting/useRenderSetting.tsx, src/enums/Storage.ts, src/hooks/usePlayback.ts, src/hooks/useSetting.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/services/PlaybackService.ts, src/stores/appStore.ts, src/types/storage.d.ts, src/utils/ChromeStorage.ts, yarn.lock
=> feat: AB repeat

src/components/player/Lyric.tsx, src/components/player/Progress.tsx, src/components/player/TrackInfo/ABSliderMenu.tsx, src/components/playlists/View.tsx, src/hooks/usePlayback.ts, src/objects/Song.ts, src/services/PlaybackService.ts, src/services/SetupService.ts, src/stores/appStore.ts, src/utils/Cache.ts, src/utils/ffmpeg.ts
abrepeat needs to be registered as headless via registerPlaybackService.
=> fix: ABRepeat event registration

src/components/player/Lyric.tsx, src/components/player/Progress.tsx, src/components/player/TrackInfo/ABSliderMenu.tsx, src/components/playlists/View.tsx, src/hooks/usePlayback.ts, src/objects/Song.ts, src/services/PlaybackService.ts, src/services/SetupService.ts, src/stores/appStore.ts, src/utils/Cache.ts, src/utils/ffmpeg.ts
=> fix: abrepeat registration

src/components/login/Bilibili.tsx, src/components/login/useBiliLoginApp.tsx, src/components/player/usePlayerControls.ts, src/components/playlist/PlaylistInfo.tsx, src/components/playlist/SongMenu.tsx, src/hooks/useSetting.ts, src/services/PlaybackService.ts, src/types/util.d.ts, src/utils/Utils.ts, src/utils/mediafetch/resolveURL.ts, src/utils/mediafetch/ytbvideo.ts
=> feat: utb suggest

package.json, src/components/dialogs/GenericCheckDialog.tsx, src/components/dialogs/GenericInputDialog.tsx, src/components/dialogs/GenericSelectDialog.tsx, src/components/login/Bilibili.tsx, src/components/login/useBiliLoginApp.tsx, src/components/player/Progress.tsx, src/components/playlist/BiliSearchbar.tsx, src/components/playlist/PlaylistInfo.tsx, src/components/playlist/PlaylistList.tsx, src/components/playlist/PlaylistMenu.tsx, src/components/playlist/PlaylistSearchMenu.tsx, src/components/playlist/SongInfo.tsx, src/components/playlist/SongMenu.tsx, src/components/setting/DeveloperSettings.tsx, src/components/styles/AzusaTheme.ts, src/components/styles/steriaGarb.json, src/enums/Playlist.ts, src/hooks/useSetting.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/utils/Logger.ts, yarn.lock
=> feat: bili cookie renew

src/components/background/MainBackground.tsx, src/components/buttons/LottieButtonAnimated.tsx, src/components/player/TrackInfo/FavoriteButton.tsx, src/components/playlist/PlaylistList.tsx, src/components/playlists/View.tsx, src/components/setting/SkinSettings.tsx, src/components/setting/View.tsx, src/components/setting/appearances/SkinSettings.tsx, src/components/setting/appearances/View.tsx, src/components/styles/AdaptiveTheme.ts, src/enums/Storage.ts, src/hooks/useSetting.ts, src/hooks/useTheme.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Playlist.ts, src/types/storage.d.ts, src/utils/Utils.ts, yarn.lock
testing out android.permission.SYSTEM_ALERT_WINDOW
=> feat: minor improvements

src/stores/appStore.ts
=> fix: regExtract

__tests__/mediafetch/bililive.test.ts, __tests__/mediafetch/bilisublive.test.ts, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/noxplay/noxplayer/MainApplication.java, android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoPackage.kt, android/build.gradle, src/components/player/View.tsx, src/objects/Song.ts, src/utils/BiliSearch.ts, src/utils/mediafetch/bilifavlist.ts, src/utils/mediafetch/bilisublive.ts, yarn.lock
mainly 2 fix the app to not hover on top of lockscreen
=> fix: minor fixes

__tests__/mediafetch/bilisublive.test.ts, android/app/build.gradle, package.json, src/enums/Version.ts, src/objects/VideoInfo.ts, src/utils/mediafetch/bilisublive.ts
need to not forget to switch branches buddy
=> chore: sync up main

android/app/src/main/java/com/noxplay/noxplayer/MainApplication.java, android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoPackage.kt
ok seriously remember to switch to dev
=> chore: name refactor

.github/workflows/jest.yml, src/components/player/Lyric.tsx, src/components/player/PIPLyric.tsx, src/components/player/PlayPauseButton.tsx, src/components/player/PlayerControls.tsx, src/components/player/PlayerModeButton.tsx, src/components/player/TrackInfo/SongMenu.tsx, src/components/player/View.tsx, src/components/player/usePlayerControls.ts, src/components/playlist/PlaylistList.tsx, src/components/playlists/ShuffleAllButton.tsx, src/components/setting/DeveloperSettings.tsx, src/components/setting/sync/PersonalCloudAuth.ts, src/hooks/usePlayback.ts, src/services/PlaybackService.ts, src/stores/appStore.ts, src/utils/Cache.ts, src/utils/RNTPUtils.ts, src/utils/ffmpeg.ts, src/utils/mediafetch/bilisublive.ts, yarn.lock
uses my native fade RNTP PR, i think refactor worked
=> feat: native fade

src/components/player/View.tsx, src/objects/Song.ts, src/services/PlaybackService.ts, src/stores/appStore.ts, src/types/request.d.ts, src/utils/BiliFetch.ts, src/utils/BiliSearch.ts, src/utils/BiliSubscribe.ts, src/utils/RNTPUtils.ts, src/utils/mediafetch/bilisublive.ts, src/utils/mediafetch/bilivideo.ts, yarn.lock
as TP.load is being phased out, now resolveURL's await time becomes noticeably long. maybe this pR helps, maybe not...
=> fix: Cache resolveURL

yarn.lock
This reverts commit 944763410f95bddc8149895703ce04f2aa79006f.
=> chore: Revert "chore: dep upgrade"

src/components/player/Lyric.tsx, src/components/player/TrackInfo/TrackInfo.tsx
- FIX: sometimes lyric would remain on the TrackInfo view.
=> bugfix: Nek ios

src/components/player/usePlayerControls.ts, src/utils/mediafetch/ytbvideo.ts, yarn.lock
[@types/react 18.2.22] breaks a bunch of stuff.
=> chore: fix dev dependency

.github/workflows/android-release.yml, src/components/setting/appearances/SkinSettings.tsx, src/utils/mediafetch/bilivideo.ts, yarn.lock
also added try_look to resolve FHD bilivideo for MainBackground;
also try if publish2googlePlay can submit and publish to internal instead of to draft
=> fix: skinSettings gesture view

ios/example/AppDelegate.h, ios/example/AppDelegate.mm, package.json, src/components/background/MainBackground.tsx, src/components/player/Lyric.tsx, src/components/player/TrackInfo/TrackInfo.tsx, src/components/player/usePlayerControls.ts, src/types/util.d.ts, src/utils/mediafetch/resolveURL.ts, src/utils/mediafetch/ytbvideo.ts
=> fix: misc fixes

src/components/player/Lyric.tsx, src/components/player/TrackInfo/AlbumArt.tsx, src/components/player/TrackInfo/TrackInfo.tsx, yarn.lock
fix this problem once and for all via scrollView's onTouchEnd and onDragEnd (i hope)
=> fix: lyric press

android/settings.gradle, ios/Podfile.lock, ios/example/Info.plist, package.json, src/components/dialogs/CopiedPlaylistDialog.tsx, src/components/dialogs/PlaylistSettingsDialog.tsx, src/components/player/TrackInfo/SongMenu.tsx, src/components/player/View.tsx, src/hooks/useActiveTrack.ts, src/hooks/useSetting.ts, src/hooks/useUpdatePlaylist.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Playlist.ts, src/types/media.d.ts, src/utils/BiliSubscribe.ts, src/utils/mediafetch/resolveURL.ts
=> feat: refresh song button

android/app/src/main/java/com/noxplay/noxplayer/MainActivity.java, android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, src/components/dialogs/NewPlaylistDialog.tsx, src/components/dialogs/PlaylistSettingsDialog.tsx, src/components/login/BiliSelectFavButtton.tsx, src/components/player/PIPLyric.tsx, src/components/player/TrackInfo/SongMenu.tsx, src/components/playlist/PlaylistMenu.tsx, src/components/playlists/Playlists.tsx, src/components/playlists/View.tsx, src/hooks/usePlaylistOperation.ts, src/hooks/useSetting.ts, src/services/PlaybackService.ts, src/utils/BiliSubscribe.ts, src/utils/ChromeStorage.ts, yarn.lock
Issue found: App doesn't perform as expected
Your app does not perform all functions properly or as expected from a user perspective.
For example, your app does not load media content in Android Auto.
=> fix: android auto review

src/components/bottomtab/NoxBottomTab.tsx, src/components/landscape/LandscapePlayerPanel.tsx, src/components/player/TrackInfo/TrackInfoTemplate.tsx, src/components/player/usePlayerControls.ts, src/components/setting/GeneralSettings.tsx, src/enums/Storage.ts, src/hooks/useSetting.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/types/storage.d.ts, src/utils/RNTPUtils.ts, src/utils/mediafetch/ytbvideo.ts
=> feat: suggestedSkipLongVideo

ios/Podfile.lock, ios/example.xcodeproj/project.pbxproj, package.json, src/components/setting/GeneralSettings.tsx, src/stores/appStore.ts, src/utils/RNTPUtils.ts, src/utils/ffmpeg.ts, yarn.lock
Winners - Reol started to rape my ears again and hopefully with this the problem is tamed.
also https://github.com/lovegaoshi/azusa-player-mobile/issues/175 is observed again with even more triggers.
=> fix: r128gain

src/components/playlist/BiliSearchbar.tsx, src/components/playlist/PlaylistList.tsx, src/hooks/usePlayback.ts, src/utils/ChromeStorage.ts, yarn.lock
data saver works for andorid auto only for now (intended)
=> feat: datasaver

src/components/player/Lyric.tsx, src/utils/fs.ts
=> fix: append writing to lrc

src/components/player/ThumbsUpButton.tsx, src/components/player/TrackInfo/SongMenuButton.tsx, src/hooks/useActiveTrack.ts, src/utils/mediafetch/bilisearch.ts
=> fix: bilisearch

src/components/player/controls/WavyAnimation.tsx
drawing too many points makes things very slow, who could hav thought!
=> fix: wavy progress

src/components/background/MainBackground.tsx, src/components/player/controls/WavyAnimation.tsx, src/utils/Cache.ts, src/utils/Gaussian.ts
=> feat: video cache

src/components/dialogs/GenericSelectDialog.tsx, src/components/player/TrackInfo/FavoriteButton.tsx, src/components/playlist/Menu/PlaylistMenu.tsx, src/components/playlist/Menu/PlaylistSortButton.tsx, src/components/playlist/Menu/usePlaylistMenu.ts, src/components/setting/plugins/r128gain/Sync.ts, src/enums/Playlist.ts, src/enums/Storage.ts, src/hooks/usePlaylist.ts, src/hooks/usePlaylistCRUD.ts, src/localization/en/translation.json, src/objects/Playlist.ts, src/services/PlaybackService.ts, src/services/SetupService.ts, src/stores/appStore.ts, src/stores/initializeStores.ts, src/stores/playerSettingStore.ts, src/stores/useApp.ts, src/types/media.d.ts, src/types/storage.d.ts, src/utils/ChromeStorage.ts, src/utils/ffmpeg/r128Store.ts, src/utils/playlistOperations.ts
=> feat: playlist sort

src/components/background/MainBackground.tsx, src/components/styles/AzusaTheme.ts, src/components/styles/NoxTheme.ts, src/components/styles/steria.json, src/components/styles/steriaGarb.json, src/types/style.d.ts, src/utils/Cache.ts, src/utils/StyleStorage.ts, src/utils/mediafetch/mainbackgroundfetch.ts
now supports landscape background
=> refactor: style

.vscode/settings.json, patches/react-native-blob-util+0.19.6.patch, src/components/dialogs/useAlert.tsx, src/components/playlist/SongList/SongMenu.tsx, src/components/playlist/usePlaylistRN.ts, src/components/styles/steria.json, src/hooks/useBiliSearch.ts, src/hooks/useInstallAPK.ts, src/hooks/useTPControls.ts, src/hooks/useVersionCheck.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/types/media.d.ts, src/utils/BiliSearch.ts, src/utils/BiliSubscribe.ts, src/utils/Bilibili/biliCookies.ts, src/utils/RNTPUtils.ts, src/utils/ffmpeg/r128RN.ts, src/utils/ffmpeg/r128Store.ts, src/utils/mediafetch/bilisearch.ts, src/utils/mediafetch/ytbmixlist.ts
adds search playlist refresh; would be our version of infinite loading
=> feat: playlist refresh

src/components/player/TrackInfo/TrackInfoTemplate.tsx, src/components/playlist/SongList/SongInfo.tsx, src/components/setting/View.tsx, src/enums/Storage.ts, src/hooks/usePlayback.ts, src/hooks/useTPControls.ts, src/stores/playingList.ts, src/stores/useApp.ts, src/types/storage.d.ts, src/utils/ChromeStorage.ts, src/utils/RNTPUtils.ts, src/utils/Utils.ts
closes #269 
still needs to refactor out currentPlayingIndex in useNoxSetting
=> refactor: currentPlayingIndex

src/utils/BiliFetch.ts, src/utils/Bilibili/biliCookies.ts, src/utils/Bilibili/bilidm.js, src/utils/mediafetch/bilichannel.ts
=> fix: biliChannel

src/components/setting/DeveloperSettings.tsx, src/services/PlaybackService.ts, src/stores/appStore.ts, yarn.lock
=> fix: showLog

android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, package.json, src/stores/initializeStores.ts
=> feat: android exit reasons

android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, src/components/player/TrackInfo/SongMenu.tsx, src/hooks/useActiveTrack.ts, src/stores/useApp.ts, src/utils/RNTPUtils.ts
=> fix: icons

index.js, src/utils/BiliSearch.ts, src/utils/RNTPUtils.ts, src/utils/mediafetch/biliAudioAM.ts, src/utils/mediafetch/biliAudioColle.ts, src/utils/mediafetch/biliAudioSimilar.ts, src/utils/mediafetch/biliaudio.ts, src/utils/mediafetch/bilichannelAudio.ts, src/utils/mediafetch/paginatedbili.ts
=> feat: b站歌单

src/enums/MediaFetch.ts, src/utils/BiliSearch.ts, src/utils/mediafetch/biliBangumi.ts, src/utils/mediafetch/biliaudio.ts, src/utils/mediafetch/resolveURL.ts
=> feat: biliBangumi

src/components/playlist/BiliSearch/Icons.tsx, src/hooks/useSetupPlayer.ts, src/utils/RNTPUtils.ts
=> fix: seekTo

src/utils/mediafetch/local.ts, src/utils/mediafetch/throttle.ts
=> fix: local playback

src/utils/SongOperations.ts
=> fix: local r128gain

index.js, package.json, patches/react-native-video+5.2.1.patch, src/components/background/MainBackground.tsx, src/hooks/useSetupPlayer.ts, yarn.lock
=> chore: revert rnv6

index.js, package.json, patches/react-native-video+5.2.1.patch, src/components/background/MainBackground.tsx, src/utils/Cache.ts, yarn.lock
This reverts commit 4eed05dcb8dd05c47810626837c184c8ca1dc564.
=> Revert "Revert "Revert "chore: rnv6 (#320)"""

docs/docs/usage-tutorial/basic.md, src/utils/BiliFetch.ts
=> fix: default UA

src/components/playlist/SongList/SongList.tsx, src/components/playlist/SongList/SongListScrollbar.tsx
=> feat: custom scroll bar

android/app/build.gradle, yarn.lock
=> feat: lyric enhancement

package.json, src/components/player/Lyric.tsx, yarn.lock
catch updateLyricMapping expecting lrcOption to be updated via setLrcOption, but state wont be refreshed during func call cycle. passing it as a param instead.
=> fix: resolved lrc mapping

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/noxplay/noxplayer/MainActivity.kt, android/app/src/main/res/values-zh/strings.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/xml/shortcuts.xml, src/App.tsx, src/components/playlists/ShuffleAllButton.tsx, src/enums/Intent.ts, src/hooks/usePlayback.ts, src/hooks/useSetupPlayer.ts, src/types/component.d.ts, src/utils/mediafetch/biliDynamic.ts, src/utils/mediafetch/biliRanking.ts
adds simple, static android app shortcuts.
=> feat: shortcuts

src/hooks/useAAPlayback.ts, src/hooks/useSetupPlayer.ts, src/stores/useApp.ts
porbably needs a refactor but oh no
=> fix: shuffleAll

src/components/player/Lyric.tsx, yarn.lock
=> feat: karaoke lyrics

src/components/explore/SongTab.tsx, src/components/explore/bilibili/View.tsx, src/enums/Playlist.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/utils/mediafetch/biliMusicTop.ts, src/utils/re.ts
=> feat: bili music weekly top discover

src/components/player/controls/ProgressWavy.tsx, src/components/player/controls/WavyAnimation.tsx, src/localization/en/translation.json, src/localization/zhcn/translation.json
=> feat: wavy progress

.gitignore, README.md, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, package.json, src/components/background/MainBackground.tsx, src/components/setting/appearances/NoWeebButton.tsx, src/components/setting/appearances/SelectDarkModeButton.tsx, src/components/setting/appearances/View.tsx, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/utils/mediafetch/mainbackgroundfetch.ts, yarn.lock
a very simple weebs be gone button to get rid of weeb background and gifs.
its still advised to DIY skin.json.
=> feat: no weeb option

android/app/src/main/java/com/noxplay/noxplayer/MainActivity.kt, src/components/setting/sync/GithubAuth.ts, src/stores/useApp.ts
=> fix: 从最爱歌单恢复播放进度

src/components/buttons/RandomGIF.tsx, src/components/dialogs/GenericCheckDialog.tsx, src/components/dialogs/GenericInputDialog.tsx, src/components/dialogs/GenericSelectDialog.tsx, src/components/player/TrackInfo/TrackInfoTemplate.tsx, src/components/playlist/BiliSearch/BiliSearchbar.tsx, src/components/playlist/View.tsx, src/components/playlist/usePlaylistRN.ts, src/components/setting/SetttingEntries.tsx, src/hooks/useBiliSearch.ts, src/hooks/usePlaylistCRUD.ts, src/stores/playingList.ts, src/stores/useApp.ts, src/types/media.d.ts, src/types/storage.d.ts, src/types/style.d.ts, src/utils/Analytics.ts, src/utils/BiliSubscribe.ts, src/utils/ChromeStorage.ts, src/utils/Utils.ts, src/utils/mediafetch/fetcher.ts, src/utils/mediafetch/paginatedfetch.ts, src/utils/playlistOperations.ts, src/utils/re.ts
=> fix: forced marquee rerender

.github/workflows/ios-weekly.yml, .github/workflows/play-release.yml, __tests__/mediafetch/biliMusicComp.test.ts, __tests__/mediafetch/biliMusicHot.test.ts, __tests__/mediafetch/biliMusicNew.test.ts, ios/example/Info.plist, src/components/explore/bilibili/View.tsx, src/components/player/Lyric.tsx, src/hooks/useLyric.ts, src/hooks/useLyricRN.ts, src/utils/mediafetch/biliMusicComp.ts, src/utils/mediafetch/biliMusicHot.ts, src/utils/mediafetch/biliMusicNew.ts
closes #426 
also refactored useLyric 
might wanna consider having a new bili explore screen for 
https://music.bilibili.com/pc/music-center
=> feat: biliExplore

src/components/player/TrackInfo/SongMenu.tsx, src/components/playlists/Playlists.tsx, src/components/setting/DeveloperSettings.tsx, src/enums/Storage.ts, src/hooks/useCleanCache.ts, src/hooks/usePlayback.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/stores/useApp.ts, src/types/storage.d.ts, src/utils/ChromeStorage.ts
implements #430;
with the mem efficiency flag on, zustand no longer hydrates songList on startup and stores the ENTIRE playlists object in mem; instead it will re-parse every time from asyncStorage
had to transform a fwe functions to async, but hope at least nothing will break with the flag OFF.
=> feat: mem efficiency flag

__tests__/utils/BiliKwSuggest.test.ts, package.json, src/components/commonui/AutoComplete.tsx, src/components/playlist/BiliSearch/BiliSearchbar.tsx, src/components/setting/DeveloperSettings.tsx, src/components/setting/GeneralSettings.tsx, src/components/setting/SkinSearchbar.tsx, src/enums/Storage.ts, src/hooks/useBiliSearch.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/types/storage.d.ts, src/types/style.d.ts, src/utils/Bilibili/BiliKwSuggest.ts, src/utils/mediafetch/biliGarb.ts, yarn.lock
=> feat: bilibili textinput suggestions

src/utils/SongOperations.ts, src/utils/ffmpeg/ffmpeg.ts, src/utils/mediafetch/local.ts
the prefetch/cache system makes this extremely complicated
hacks! hacks! hacks!
=> fix: album art resovle path

android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt, src/components/styles/AzusaTheme.ts, src/utils/mediafetch/bilisearch.ts
=> fix: bunch of stuff

package.json, yarn.lock
=> chore: dep upgarde

.github/workflows/play-release.yml, __tests__/mediafetch/ytbvideo.test.ts
=> fix: gh actions

src/hooks/usePlayback.ts, src/stores/useApp.ts
sentry triggered playfromsearch query === '' but htere is no playlist.? this should catch it
=> fix: playstore review

src/utils/mediafetch/alist.ts
now works with https://al.nn.ci/ (no cred)
233510.xyz is slow af but wth
=> fix: alist

src/components/player/controls/usePlayerControls.ts
repeat-one still "loads" the media into exoplayer. so we detect that via a loading state tracker and process AB loop if the loading state is previously detected.
closes #509
=> fix: repeat-one ABLoop

src/components/setting/appearances/SkinSettings.tsx
at the skin selection screen, on holding will bring out a dialog to select the background; no need to play the lottery anymore
=> feat: skin select

src/utils/mediafetch/ytbvideo.ts
node-ytdl failed again. resolving to ytm for now
=> fix: ytb resolve order

src/components/player/controls/usePlayerControls.ts, src/components/setting/GeneralSettings.tsx, src/hooks/useTPControls.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Storage.ts, src/stores/playingList.ts, src/types/storage.d.ts, src/utils/mediafetch/ytbLive.ts, src/utils/mediafetch/ytbPlaylist.ts
=> feat: no repeat

src/hooks/useSetupPlayer.ts, src/utils/mediafetch/ytbi.ts
=> fix: ytbi load time

__tests__/lyricfetch/lrclib.test.ts, metro.config.js, src/enums/LyricFetch.ts, src/utils/lrcfetch/lrclib.ts
closes #549 
i dont think lrclib is that useful right now so its not built in yet.
=> feat: lrclib

ios/Podfile.lock, package.json, yarn.lock
=> fix: wake lock

src/components/player/controls/usePlayerControls.ts, src/components/setting/DeveloperSettings.tsx
seems like crossfade competes with fade when ABrepeat is set?
=> fix: crossfade

src/services/PlaybackService.ts
This reverts commit 737086017e9095ad2297de12a819d0e7adadb478.
=> Revert "fix: crossfade"

src/components/setting/alist/CredDialog.tsx
=> fix: alist pwd

.gitignore, src/components/explore/SongTab.tsx, src/components/explore/ytmusic/View.tsx, src/components/explore/ytmusic/useYTMExplore.tsx, src/components/player/controls/usePlayerControls.ts, src/localization/zhcn/translation.json, src/utils/mediafetch/ytbPlaylist.muse.ts, src/utils/mediafetch/ytbSearch.muse.ts, src/utils/mediafetch/ytbmixlist.ts, src/utils/mediafetch/ytbvideo.muse.ts
=> fix: abrepeat on repeat.Track 

src/utils/BiliFetch.ts, src/utils/Bilibili/biliWebid.ts, src/utils/RNTPUtils.ts, src/utils/mediafetch/bilichannel.ts, src/utils/mediafetch/biliuser.ts
=> fix: biliWebid

android/build.gradle, src/components/player/controls/usePlayerControls.ts
=> fix: build

android/gradle.properties, package.json, patches/react-native-tab-view+4.0.1.patch, yarn.lock
tracks https://github.com/react-navigation/react-navigation/issues/12251
=> fix: new arch

android/gradle.properties, src/AzusaPlayer.tsx
tracks https://github.com/facebook/react-native/issues/47490#issuecomment-2478859368 until resolved
=> chore: disable newarch

package.json, yarn.lock
wait for multiline lrc implementation
=> fix: lyric

src/components/commonui/HorizontalCarousel.tsx, src/components/miniplayer/Artwork.tsx, src/components/playlists/Playlists.tsx, src/hooks/useVIP.ts, src/stores/useSnack.ts
=> fix: artwork carousel

src/hooks/useActiveTrack.ts, src/hooks/useSetupPlayer.ts
=> fix: fix: useActiveTrack

src/components/setting/appearances/SkinSettings.tsx
=> fix: skin setting animation

src/components/login/google/YTM.tsx
=> fix: ytm login

src/utils/BiliSearch.ts, src/utils/mediafetch/mainbackgroundfetch.ts, src/utils/mediafetch/ytbChannel.ytbi.ts
=> fix: ytb chan

src/components/player/controls/usePlayerControls.ts, src/components/playlist/usePlaylistRN.ts, src/hooks/usePlaylist.ts
=> fix: playSong's currentPlayingList

src/components/dialogs/NoxInput.tsx, src/components/miniplayer/View.tsx, src/components/playlist/BiliSearch/BiliSearchbar.tsx, src/components/playlists/Playlists.tsx, src/components/setting/appearances/NoWeebDialog.tsx, src/components/styles/AzusaThemeRaw.ts, src/stores/useAPMUI.ts
=> feat: miniplayer collapse on sharemenu

src/utils/BiliSearch.ts, src/utils/mediafetch/bilicolle.ts, src/utils/mediafetch/biliseries.ts
=> feat: biliseries new url format

android/app/proguard-rules.pro, android/ffmpeg-kit-binaries/build.gradle.kts, android/settings.gradle, package.json, src/components/bottomtab/NoxBottomTab.tsx, src/components/playlists/Playlists.tsx, src/components/setting/appearances/View.tsx, src/hooks/useLyric.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Storage.ts, src/types/storage.d.ts, src/utils/ChromeStorage.ts, src/utils/ChromeStorageAPI.ts, yarn.lock
=> fix: asyncstorage race condition

package.json, yarn.lock
closes #768 
this is caused by marquee's animation position not being reset to 0 when text changes. in fact i dont even see stopAnimation ever being called. when changing from a long text to a short text, this.animationValue is still at whatever animated value was and the short text position is no longer correct.
=> fix: marquee text

__mocks__/expo-sqlite/kv-store.js, __tests__/mediafetch/biliRanking.test.ts, jest.config.js, src/enums/MediaFetch.ts, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/stores/explore/bilibili.ts, src/utils/mediafetch/biliRanking.ts
also fixes jest (expo-sqlite mock)
closes #770
=> feat: biliranking

src/components/playlist/Menu/PlaylistMenuButton.tsx, src/stores/useAndroidAuto.ts
=> fix: AA i18n

src/stores/appStore.ts
=> fix: abrepeat on first song

android/app/src/main/java/com/noxplay/noxplayer/NoxModule.kt, src/components/setting/developer/DeveloperSettings.tsx, src/utils/ChromeStorage.ts, src/utils/RNUtils.ts
fixes newarch sentry.nativeCrash doesnt work for some reason, by using android.os.Process.killProcess
=> feat: alternative android native crash

src/components/playlist/SongList/SongList.tsx, src/components/playlist/SongList/SongListScrollbar.tsx
=> fix: scrollbar

src/utils/Bilibili/biliWebid.ts
fixes getUserInfo and getBiliChannel
=> fix: w_webid deprecated?

package.json, patches/react-native-ota-hot-update+2.2.2.patch, yarn.lock
=> chore: dep upg

src/components/playlist/SongList/View.tsx, src/components/playlist/View.tsx
=> fix: bilisearchbar onSearch does a scrollTo

patches/@lodev09+react-native-true-sheet+2.0.5.patch, src/components/dialogs/GenericSelectDialog.tsx
=> fix: true sheet onPress

src/components/playlist/usePlaylistRN.ts
=> fix: playlist repeatmode exec order

src/App.tsx, src/components/background/AccentColorBackground.tsx, src/components/background/MainBackground.tsx
=> chore: refactor children out of mainbackground

ios/example/Info.plist
=> fix: react native vector icons ios

android/app/src/main/java/com/noxplay/noxplayer/MainActivity.kt, android/app/src/main/java/com/noxplay/noxplayer/NoxModule.kt, src/components/setting/appearances/SkinSettings.tsx, src/hooks/useTanakaAmazingCommodities.ts, src/stores/initializeStores.ts, src/utils/ChromeStorageAPI.ts, src/utils/RNUtils.ts
=> fix: android dark theme

src/App.tsx, src/components/commonui/Snackbar.tsx, src/components/styles/Theme.ts
=> fix: snackbar theme

src/components/playlist/Info/PlaylistInfo.tsx
=> fix: playlist searchbar height

src/components/songmenu/SongMenuSheet.tsx, src/localization/en/translation.json, src/localization/zhcn/translation.json
=> feat: share btn

ios/Podfile, package.json, src/components/APMPortrait.tsx, src/components/bottomtab/NoxBottomTab.tsx, src/components/bottomtab/NoxNativeBottomTab.tsx, src/components/bottomtab/View.tsx, src/components/miniplayer/Artwork.tsx, src/components/miniplayer/View.tsx, src/components/player/TrackInfo/AlbumArt.tsx, src/components/setting/appearances/AppearanceSetting.tsx, src/localization/en/translation.json, src/localization/zhcn/translation.json, src/objects/Storage.ts, src/types/storage.d.ts, yarn.lock
=> feat: native bottom tab

src/components/setting/appearances/SkinSettings.tsx, src/utils/mediafetch/ytbPlaylist.ts, src/utils/mediafetch/ytbPlaylist.ytbi.ts
also fixes dark theme
closes #958 
closes #961
=> feat: yt limit

android/gradle.properties
=> feat: new arch

src/utils/playlistOperations.ts
closes [#9](https://github.com/lovegaoshi/NoxPlayer/issues/130)
=> feat: sort by date

patches/react-native-share-menu+6.0.0.patch
=> fix: ios build

src/components/bottomtab/NoxBottomTab.tsx, src/components/bottomtab/NoxNativeBottomTab.tsx, src/components/playlists/View.tsx, src/hooks/useDrawerStatus.ts, src/stores/useBottomTab.ts, src/utils/useLazyEffect.ts
=> fix: drawer bottom tab

src/components/player/Lyric.tsx, src/hooks/useLyric.ts
=> feat: useLyric loading

src/components/miniplayer/Artwork.tsx, src/components/miniplayer/View.tsx, src/components/setting/appearances/SkinSettings.tsx, src/components/styles/SolidTheme.ts, src/hooks/useSetupPlayer.ts, src/utils/ChromeStorageAPI.ts
=> feat: solid color theme

src/hooks/useSetupPlayer.ts, src/utils/mediafetch/ytbChannel.ytbi.ts
=> feat: yt channel limit

src/components/commonui/bottomsheet/NoxBottomSheet.tsx, src/components/explore/View.tsx, src/components/landscape/APMLandscape.tsx, src/components/landscape/LandscapeActions.tsx, src/components/landscape/LandscapePlaylistPanel.tsx, src/components/player/Lyric.tsx, src/components/playlist/View.tsx, src/components/playlist/usePlaylistRN.ts
=> fix: various fixes 

src/components/player/controls/usePlayerControls.ts, src/components/player/controls/useSponsorBlock.ts
=> fix: sponsorblock

src/components/commonui/DelayedComponent.tsx, src/components/explore/View.tsx, src/components/setting/helpers/BooleanSetting.tsx
fixes (some of ) teh explore page delay.
=> feat: delayed component

ios/APM.xcodeproj/project.pbxproj, ios/Podfile.lock, src/components/miniplayer/View.tsx, src/hooks/usePlayback.migrate.ts, src/hooks/usePlayback.ts, src/stores/useApp.ts
=> fix: various stuff
