lovegaoshi/azusa-player-mobile

android/settings.gradle
ios/Podfile
package.json
src/components/buttons/PlaylistMenuButton.tsx
src/components/buttons/PlaylistSettingsButton.tsx
src/components/dialogs/CopiedPlaylistDialog.tsx
src/components/dialogs/PlaylistSettingsDialog.tsx
src/components/playlist/BiliSearchbar.tsx
src/components/playlist/PlaylistList.tsx
src/components/playlist/PlaylistMenu.tsx
src/components/playlist/SongMenu.tsx
src/components/playlists/View.tsx
src/enums/Playlist.ts
src/hooks/useSetting.ts
src/objects/Playlist.ts
src/objects/SongOperations.ts
src/utils/ChromeStorage.ts
src/utils/DataProcess.js
src/utils/Utils.ts
yarn.lock

移植歌单菜单功能：改名，b站识歌，清空歌单，删除歌单，重载歌单，统计，把歌单1加入歌单2
另外的改动：
@kenmingwang 修正settings.gradle和podfile(?)里文件夹改名（example->azusa-player-mobile）；用android Studio重sync和run app后，可以正常运行
progressEmitter in BiliSearchbar.ts 移至zustand store下

feat: Playlist Menu 

---

src/components/player/PlayerModeButton.tsx

// NOTE: DO NOT CHANGE THIS TO OTHER MODES!
// APM uses zustand handles queue so it relies on
// RepeatMode.Off to properly trigger PlaybackQueueEnded
// and call zustand to load the next song in queue. this must be
// RepeatMode.Off.

fix: repeatMode

---

src/App.tsx
src/AzusaPlayer.tsx
src/components/player/TrackInfo/SongMenu.tsx
src/components/playlist/BiliSearchbar.tsx
src/components/playlists/View.tsx
src/hooks/usePlayback.ts
src/services/PlaybackService.ts

reverts it back to PlaybackService.ts. TrackPlayer when loading the first Track loads too fast before its mounted in a component (it works in debug... not release). 
we can either do this and use a vanilla store to track resolved metadata from PlaybackActiveTrackChanged, or ask TrackPlayer to resolve again at load. second might be a good idea too

fix: playback listener mount time

---

src/utils/mediafetch/ytbvideo.ts

iOS yt resolved duration for audio only mp4a streams has doubled duration; ogg streams are not playable, mp4a video + audio seems to work fine.

fix(ios): yt duration

---

android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt
babel.config.js
package.json
src/AzusaPlayer.tsx
src/components/bottomtab/NoxBottomTab.tsx
src/components/player/Lyric.tsx
src/components/player/PlayerControls.tsx
src/components/player/TrackInfo/SongMenu.tsx
src/components/playlist/PlaylistInfo.tsx
src/components/playlist/PlaylistList.tsx
src/hooks/usePlayback.ts
src/utils/Data.js
src/utils/Data.ts
src/utils/mediafetch/mfsdk.ts
yarn.lock

feat: bottom tab

---

src/hooks/usePlayback.ts

I wrapped SongInfo's playSong into a wrapper. within the wrapper useActiveTrack().song is correct as the previous song, but then in playSong useActiveTrack().song is the scheduled next song. This sounds like a serious bug but oh well.

fix: no playsong logic

---

package.json
src/components/player/Lyric.tsx
src/components/player/TrackInfo/TrackInfoTemplate.tsx
src/hooks/useCleanCache.ts
src/services/PlaybackService.ts
src/utils/ChromeStorage.ts
src/utils/fs.ts
yarn.lock

closes #227 
lyrics are now written in appdir/documents/lyrics/*.txt;
if lyrics can be read, load;
if lyrics doesnt have .txt in it, show lyrics;
else, load search
======
we might need to refactor some Lyrics because the setStates wont work as expected as they will only be updated in the next refresh cycle. but hey it works. dont touch it then

fix: local lyrics

---

src/components/player/controls/WavyAnimation.tsx
src/components/playlist/SongList/SongList.tsx
src/components/playlists/ShuffleAllButton.tsx
src/hooks/useDataSaver.ts
src/hooks/usePlayback.ts
src/hooks/useTPControls.ts

because I didnt record the current playing Index but rather determine the index every time via findIndex, this really relies ona songlist's songs being unique on id; this is generally true because updatePlaylist does a songs filter, but not in shuffleAll. this will make playing shuffle all playlist sometimes jumpy as a later song's id was found earlier. 
this is typically not a big problem bc shuffle all is usually a very large playlist; but when filtering to cached songs this is very problematic. theres  not a good workaround, eh. filtering at shuffle all seems slowish (i have 300k song total of playlists). i opted to filter for cached and unique songs when dataSaver is enabled during shuffle all.

fix: shuffleAll unique songslist

---

src/components/playlist/Menu/PlaylistMenu.tsx
src/components/playlist/Menu/PlaylistMenuButton.tsx
src/components/playlist/SongList/SongList.tsx
src/components/setting/GeneralSettings.tsx

prevent a recyclingview? bug where the previous content is lingering in flashlist somehow, by setting the data to empty beforehand to clear content first. performance hit is beyter than a bug

fix: songlist update view

---

__tests__/mediafetch/biliFavColle.test.ts
src/utils/BiliSearch.ts
src/utils/mediafetch/biliFavColle.ts

for
https://space.bilibili.com/529249/favlist?fid=1061551&ftype=collect&ctype=21
closes #387

feat: biliFavColle

---

src/utils/mediafetch/resolveURL.ts

closes #419 
exposes fetchPlayUrlPromise onError to a null track that gives an error in RNTP.

fix: expose playURL error to RNTP

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt
android/app/src/main/res/xml/provider_paths.xml
src/utils/mediafetch/local.ts

feat: fileContentProvider resolver

---

android/app/src/main/java/com/noxplay/noxplayer/NoxAndroidAutoModule.kt
src/components/setting/DeveloperSettings.tsx
src/enums/Storage.ts
src/utils/mediafetch/local.ts

skips ffmpeg resolve local artwork if possible, since the embedded image is being cached to /Pictures anyways.

feat: resolveArtwork native

---

src/hooks/useSetupPlayer.ts
src/utils/mediafetch/resolveURL.ts
src/utils/mediafetch/ytbSearch.ytbi.ts
src/utils/mediafetch/ytbi.ts
src/utils/mediafetch/ytbvideo.ts
src/utils/mediafetch/ytbvideo.ytbi.ts

ytbi init (retrieve_player) must be true. i thought its not necessary bc it is caught by using ytm to resolve. 
so ytm will now be used to resolve by default; and a new function separate from resolveURL to refresh metadata is added. for some reason ytm's metadata (really, cover) is not highres.

fix: ytbi thumbnail resolve

---

src/components/miniplayer/Artwork.tsx
src/components/miniplayer/Lrc.tsx
src/components/miniplayer/MiniControls.tsx
src/components/miniplayer/TrackInfo.tsx
src/components/player/TrackInfo/SongMenu.tsx
src/components/player/controls/ThumbsUpButton.tsx
src/components/player/controls/usePlayerControls.ts
src/hooks/useAccentColor.ts
src/hooks/useActiveTrack.ts
src/hooks/useSetupPlayer.ts
src/stores/useApp.ts

properly implement activeTrack as a global store

fix: useActiveTrack

---

package.json
patches/expo-image+2.0.2.patch
yarn.lock

fix: expo-image

---

android/gradle.properties
src/components/playlists/View.tsx

fix: newarch perf

---

src/components/miniplayer/View.tsx

fix #688 by initializing the miniplayer to be mini, but expand upon startup to get the correct height when flexing

ffix: newarch perf

---

src/components/miniplayer/View.tsx
src/components/playlists/View.tsx
src/stores/useAPMUI.ts

i HATE new arch workarounds HATE HATE HATE HATE

fix: drwaer content

---

.github/workflows/android-release.yml
.github/workflows/ios-weekly.yml

now thinking about it, it should be when i used the old arch flag in yarn ios:build but its not in ghactions's yml 
closes #702

fix: ios build

---

src/components/player/controls/usePlayerControls.ts
src/hooks/usePlayback.migrate.ts
src/hooks/useTPControls.ts
src/stores/playingList.ts

need to refactor the playback logic. so now the play next logic is dictated by playingList store's currentPlayingIndex
previously playNext/Previous is done by moving the playback index, get the song, insert if needed, then TP.skipToNext/Previous. with crossfade it pre-inserts the song but to get the song it moves the playback index as well, making crossfade jumping around the queue by quite a lot. here the TP.crossfadePrepare is updated to NOT move the playback index, but rather the index moving is happing at TP.crossfade
its still a rather inconsistent solution that will bite me in the butt later

fix: crossfade

---

src/components/commonui/RefreshIndicator.tsx
src/components/explore/SongTab.tsx
src/components/explore/View.tsx
src/components/playlist/SongList/SongList.tsx
src/components/playlist/usePlaylistRN.ts
src/hooks/usePlaylist.ts
src/hooks/usePlaylistCRUD.ts
src/utils/BiliSubscribe.ts

adds a pull up to refresh functionality for search playlists; songs will be added to the bottom of the playlist instead of top. 
https://blog.cloudboost.io/building-a-custom-refresh-animation-in-react-native-using-reanimated-9b64212a0366 but in reverse

feat: pull up to refresh
